[project]
name = "artifacts"
version = "0.1.0"
description = "Basic CPU Pyproject setup for EDA project"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tensorflow>=2.20.0",
]
